"""empty message

Revision ID: 428331ce0561
Revises: 
Create Date: 2017-01-22 15:45:17.520831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428331ce0561'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
